/*
 * [Warning!] This file is auto-generated by pika compiler.
 * Do not edit it manually.
 * The source code is *.pyi file.
 * More details: 
 * English Doc:
 * https://pikadoc-en.readthedocs.io/en/latest/PikaScript%20%E6%A8%A1%E5%9D%97%E6%A6%82%E8%BF%B0.html
 * Chinese Doc:
 * http://pikapython.com/doc/PikaScript%20%E6%A8%A1%E5%9D%97%E6%A6%82%E8%BF%B0.html
 */

#ifndef __pika_lvgl_label__H
#define __pika_lvgl_label__H
#include <stdio.h>
#include <stdlib.h>
#include "PikaObj.h"

PikaObj *New_pika_lvgl_label(Args *args);

void pika_lvgl_label___init__(PikaObj *self, PikaObj* parent);
void pika_lvgl_label_cut_text(PikaObj *self, int pos, int cnt);
int pika_lvgl_label_get_letter_on(PikaObj *self, PikaObj* pos_in);
PikaObj* pika_lvgl_label_get_letter_pos(PikaObj *self, int char_id);
int pika_lvgl_label_get_long_mode(PikaObj *self);
int pika_lvgl_label_get_recolor(PikaObj *self);
char* pika_lvgl_label_get_text(PikaObj *self);
int pika_lvgl_label_get_text_selection_end(PikaObj *self);
int pika_lvgl_label_get_text_selection_start(PikaObj *self);
void pika_lvgl_label_ins_text(PikaObj *self, int pos, char* txt);
int pika_lvgl_label_is_char_under_pos(PikaObj *self, PikaObj* pos);
void pika_lvgl_label_set_long_mode(PikaObj *self, int long_mode);
void pika_lvgl_label_set_recolor(PikaObj *self, int en);
void pika_lvgl_label_set_text(PikaObj *self, char* txt);
void pika_lvgl_label_set_text_sel_end(PikaObj *self, int index);
void pika_lvgl_label_set_text_sel_start(PikaObj *self, int index);
void pika_lvgl_label_set_text_static(PikaObj *self, char* txt);

#endif
