/*
 * [Warning!] This file is auto-generated by pika compiler.
 * Do not edit it manually.
 * The source code is *.pyi file.
 * More details: 
 * English Doc:
 * https://pikadoc-en.readthedocs.io/en/latest/PikaScript%20%E6%A8%A1%E5%9D%97%E6%A6%82%E8%BF%B0.html
 * Chinese Doc:
 * http://pikapython.com/doc/PikaScript%20%E6%A8%A1%E5%9D%97%E6%A6%82%E8%BF%B0.html
 */

#ifndef __pika_lvgl_chart__H
#define __pika_lvgl_chart__H
#include <stdio.h>
#include <stdlib.h>
#include "PikaObj.h"

PikaObj *New_pika_lvgl_chart(Args *args);

void pika_lvgl_chart___init__(PikaObj *self, PikaObj* parent);
PikaObj* pika_lvgl_chart_add_cursor(PikaObj *self, PikaObj* color, int dir);
PikaObj* pika_lvgl_chart_add_series(PikaObj *self, PikaObj* color, int axis);
PikaObj* pika_lvgl_chart_get_cursor_point(PikaObj *self, PikaObj* cursor);
int pika_lvgl_chart_get_point_count(PikaObj *self);
PikaObj* pika_lvgl_chart_get_point_pos_by_id(PikaObj *self, PikaObj* ser, int id);
int pika_lvgl_chart_get_pressed_point(PikaObj *self);
PikaObj* pika_lvgl_chart_get_series_next(PikaObj *self, PikaObj* ser);
int pika_lvgl_chart_get_type(PikaObj *self);
Arg* pika_lvgl_chart_get_x_array(PikaObj *self, PikaObj* ser);
int pika_lvgl_chart_get_x_start_point(PikaObj *self, PikaObj* ser);
Arg* pika_lvgl_chart_get_y_array(PikaObj *self, PikaObj* ser);
int pika_lvgl_chart_get_zoom_x(PikaObj *self);
int pika_lvgl_chart_get_zoom_y(PikaObj *self);
void pika_lvgl_chart_hide_series(PikaObj *self, PikaObj* series, int hide);
void pika_lvgl_chart_refresh(PikaObj *self);
void pika_lvgl_chart_remove_series(PikaObj *self, PikaObj* series);
void pika_lvgl_chart_set_all_value(PikaObj *self, PikaObj* ser, int value);
void pika_lvgl_chart_set_axis_tick(PikaObj *self, int axis, int major_len, int minor_len, int major_cnt, int minor_cnt, int label_en, int draw_size);
void pika_lvgl_chart_set_cursor_point(PikaObj *self, PikaObj* cursor, PikaObj* ser, int point_id);
void pika_lvgl_chart_set_cursor_pos(PikaObj *self, PikaObj* cursor, PikaObj* pos);
void pika_lvgl_chart_set_div_line_count(PikaObj *self, int hdiv, int vdiv);
void pika_lvgl_chart_set_ext_x_array(PikaObj *self, PikaObj* ser, Arg* array);
void pika_lvgl_chart_set_ext_y_array(PikaObj *self, PikaObj* ser, Arg* array);
void pika_lvgl_chart_set_next_value(PikaObj *self, PikaObj* ser, int value);
void pika_lvgl_chart_set_next_value2(PikaObj *self, PikaObj* ser, int x_value, int y_value);
void pika_lvgl_chart_set_point_count(PikaObj *self, int cnt);
void pika_lvgl_chart_set_range(PikaObj *self, int axis, int min, int max);
void pika_lvgl_chart_set_series_color(PikaObj *self, PikaObj* series, PikaObj* color);
void pika_lvgl_chart_set_type(PikaObj *self, int type);
void pika_lvgl_chart_set_update_mode(PikaObj *self, int update_mode);
void pika_lvgl_chart_set_value_by_id(PikaObj *self, PikaObj* ser, int id, int value);
void pika_lvgl_chart_set_value_by_id2(PikaObj *self, PikaObj* ser, int id, int x_value, int y_value);
void pika_lvgl_chart_set_x_start_point(PikaObj *self, PikaObj* ser, int id);
void pika_lvgl_chart_set_zoom_x(PikaObj *self, int zoom_x);
void pika_lvgl_chart_set_zoom_y(PikaObj *self, int zoom_y);

#endif
