/*
 * [Warning!] This file is auto-generated by pika compiler.
 * Do not edit it manually.
 * The source code is *.pyi file.
 * More details: 
 * English Doc:
 * https://pikadoc-en.readthedocs.io/en/latest/PikaScript%20%E6%A8%A1%E5%9D%97%E6%A6%82%E8%BF%B0.html
 * Chinese Doc:
 * http://pikapython.com/doc/PikaScript%20%E6%A8%A1%E5%9D%97%E6%A6%82%E8%BF%B0.html
 */

#ifndef __pika_lvgl_lv_obj__H
#define __pika_lvgl_lv_obj__H
#include <stdio.h>
#include <stdlib.h>
#include "PikaObj.h"

PikaObj *New_pika_lvgl_lv_obj(Args *args);

void pika_lvgl_lv_obj___init__(PikaObj *self, PikaObj* parent);
void pika_lvgl_lv_obj_add_event_cb(PikaObj *self, Arg* event_cb, int filter, void* user_data);
void pika_lvgl_lv_obj_add_flag(PikaObj *self, int flag);
void pika_lvgl_lv_obj_add_state(PikaObj *self, int state);
void pika_lvgl_lv_obj_add_style(PikaObj *self, PikaObj* style, int selector);
void pika_lvgl_lv_obj_align(PikaObj *self, int align, int x_ofs, int y_ofs);
void pika_lvgl_lv_obj_align_to(PikaObj *self, PikaObj* base, int align, int x_ofs, int y_ofs);
void pika_lvgl_lv_obj_center(PikaObj *self);
void pika_lvgl_lv_obj_clean(PikaObj *self);
void pika_lvgl_lv_obj_clear_flag(PikaObj *self, int flag);
void pika_lvgl_lv_obj_del_(PikaObj *self);
int pika_lvgl_lv_obj_get_content_height(PikaObj *self);
int pika_lvgl_lv_obj_get_content_width(PikaObj *self);
int pika_lvgl_lv_obj_get_height(PikaObj *self);
char* pika_lvgl_lv_obj_get_id(PikaObj *self);
int pika_lvgl_lv_obj_get_scroll_bottom(PikaObj *self);
int pika_lvgl_lv_obj_get_scroll_dir(PikaObj *self);
int pika_lvgl_lv_obj_get_scroll_left(PikaObj *self);
int pika_lvgl_lv_obj_get_scroll_right(PikaObj *self);
int pika_lvgl_lv_obj_get_scroll_snap_x(PikaObj *self);
int pika_lvgl_lv_obj_get_scroll_snap_y(PikaObj *self);
int pika_lvgl_lv_obj_get_scroll_top(PikaObj *self);
int pika_lvgl_lv_obj_get_scroll_x(PikaObj *self);
int pika_lvgl_lv_obj_get_scroll_y(PikaObj *self);
int pika_lvgl_lv_obj_get_scrollbar_mode(PikaObj *self);
int pika_lvgl_lv_obj_get_self_height(PikaObj *self);
int pika_lvgl_lv_obj_get_self_width(PikaObj *self);
int pika_lvgl_lv_obj_get_width(PikaObj *self);
int pika_lvgl_lv_obj_get_x(PikaObj *self);
int pika_lvgl_lv_obj_get_x2(PikaObj *self);
int pika_lvgl_lv_obj_get_x_aligned(PikaObj *self);
int pika_lvgl_lv_obj_get_y(PikaObj *self);
int pika_lvgl_lv_obj_get_y2(PikaObj *self);
int pika_lvgl_lv_obj_get_y_aligned(PikaObj *self);
int pika_lvgl_lv_obj_hit_test(PikaObj *self, PikaObj* point);
void pika_lvgl_lv_obj_invalidate(PikaObj *self);
int pika_lvgl_lv_obj_is_layout_positioned(PikaObj *self);
int pika_lvgl_lv_obj_is_visible(PikaObj *self);
void pika_lvgl_lv_obj_mark_layout_as_dirty(PikaObj *self);
void pika_lvgl_lv_obj_move_background(PikaObj *self);
void pika_lvgl_lv_obj_move_children_by(PikaObj *self, int x_diff, int y_diff, int ignore_floating);
void pika_lvgl_lv_obj_move_foreground(PikaObj *self);
void pika_lvgl_lv_obj_move_to(PikaObj *self, int x, int y);
void pika_lvgl_lv_obj_refr_pos(PikaObj *self);
int pika_lvgl_lv_obj_refr_size(PikaObj *self);
int pika_lvgl_lv_obj_refresh_self_size(PikaObj *self);
void pika_lvgl_lv_obj_remove_style_all(PikaObj *self);
void pika_lvgl_lv_obj_scroll_to_view(PikaObj *self, int anim_en);
void pika_lvgl_lv_obj_scroll_to_view_recursive(PikaObj *self, int anim_en);
void pika_lvgl_lv_obj_set_align(PikaObj *self, int align);
void pika_lvgl_lv_obj_set_content_height(PikaObj *self, int h);
void pika_lvgl_lv_obj_set_content_width(PikaObj *self, int w);
void pika_lvgl_lv_obj_set_ext_click_area(PikaObj *self, int size);
void pika_lvgl_lv_obj_set_flex_align(PikaObj *self, int main_place, int cross_place, int align);
void pika_lvgl_lv_obj_set_flex_flow(PikaObj *self, int flow);
void pika_lvgl_lv_obj_set_flex_grow(PikaObj *self, int value);
void pika_lvgl_lv_obj_set_height(PikaObj *self, int h);
void pika_lvgl_lv_obj_set_id(PikaObj *self, char* id);
void pika_lvgl_lv_obj_set_layout(PikaObj *self, int layout);
void pika_lvgl_lv_obj_set_pos(PikaObj *self, int x, int y);
void pika_lvgl_lv_obj_set_scroll_dir(PikaObj *self, int dir);
void pika_lvgl_lv_obj_set_scroll_snap_x(PikaObj *self, int align);
void pika_lvgl_lv_obj_set_scroll_snap_y(PikaObj *self, int align);
void pika_lvgl_lv_obj_set_scrollbar_mode(PikaObj *self, int mode);
void pika_lvgl_lv_obj_set_size(PikaObj *self, int w, int h);
void pika_lvgl_lv_obj_set_style_align(PikaObj *self, int value, int selector);
void pika_lvgl_lv_obj_set_style_anim_speed(PikaObj *self, int value, int selector);
void pika_lvgl_lv_obj_set_style_anim_time(PikaObj *self, int value, int selector);
void pika_lvgl_lv_obj_set_style_arc_color(PikaObj *self, PikaObj* value, int selector);
void pika_lvgl_lv_obj_set_style_arc_opa(PikaObj *self, int value, int selector);
void pika_lvgl_lv_obj_set_style_arc_rounded(PikaObj *self, int value, int selector);
void pika_lvgl_lv_obj_set_style_arc_width(PikaObj *self, int value, int selector);
void pika_lvgl_lv_obj_set_style_base_dir(PikaObj *self, int value, int selector);
void pika_lvgl_lv_obj_set_style_bg_color(PikaObj *self, PikaObj* value, int selector);
void pika_lvgl_lv_obj_set_style_bg_dither_mode(PikaObj *self, int value, int selector);
void pika_lvgl_lv_obj_set_style_bg_grad_color(PikaObj *self, PikaObj* value, int selector);
void pika_lvgl_lv_obj_set_style_bg_grad_dir(PikaObj *self, int value, int selector);
void pika_lvgl_lv_obj_set_style_bg_grad_stop(PikaObj *self, int value, int selector);
void pika_lvgl_lv_obj_set_style_bg_img_opa(PikaObj *self, int value, int selector);
void pika_lvgl_lv_obj_set_style_bg_img_recolor(PikaObj *self, PikaObj* value, int selector);
void pika_lvgl_lv_obj_set_style_bg_img_recolor_opa(PikaObj *self, int value, int selector);
void pika_lvgl_lv_obj_set_style_bg_img_tiled(PikaObj *self, int value, int selector);
void pika_lvgl_lv_obj_set_style_bg_main_stop(PikaObj *self, int value, int selector);
void pika_lvgl_lv_obj_set_style_bg_opa(PikaObj *self, int value, int selector);
void pika_lvgl_lv_obj_set_style_blend_mode(PikaObj *self, int value, int selector);
void pika_lvgl_lv_obj_set_style_border_color(PikaObj *self, PikaObj* value, int selector);
void pika_lvgl_lv_obj_set_style_border_opa(PikaObj *self, int value, int selector);
void pika_lvgl_lv_obj_set_style_border_post(PikaObj *self, int value, int selector);
void pika_lvgl_lv_obj_set_style_border_side(PikaObj *self, int value, int selector);
void pika_lvgl_lv_obj_set_style_border_width(PikaObj *self, int value, int selector);
void pika_lvgl_lv_obj_set_style_clip_corner(PikaObj *self, int value, int selector);
void pika_lvgl_lv_obj_set_style_color_filter_opa(PikaObj *self, int value, int selector);
void pika_lvgl_lv_obj_set_style_height(PikaObj *self, int value, int selector);
void pika_lvgl_lv_obj_set_style_img_opa(PikaObj *self, int value, int selector);
void pika_lvgl_lv_obj_set_style_img_recolor(PikaObj *self, PikaObj* value, int selector);
void pika_lvgl_lv_obj_set_style_img_recolor_opa(PikaObj *self, int value, int selector);
void pika_lvgl_lv_obj_set_style_layout(PikaObj *self, int value, int selector);
void pika_lvgl_lv_obj_set_style_line_color(PikaObj *self, PikaObj* value, int selector);
void pika_lvgl_lv_obj_set_style_line_dash_gap(PikaObj *self, int value, int selector);
void pika_lvgl_lv_obj_set_style_line_dash_width(PikaObj *self, int value, int selector);
void pika_lvgl_lv_obj_set_style_line_opa(PikaObj *self, int value, int selector);
void pika_lvgl_lv_obj_set_style_line_rounded(PikaObj *self, int value, int selector);
void pika_lvgl_lv_obj_set_style_line_width(PikaObj *self, int value, int selector);
void pika_lvgl_lv_obj_set_style_max_height(PikaObj *self, int value, int selector);
void pika_lvgl_lv_obj_set_style_max_width(PikaObj *self, int value, int selector);
void pika_lvgl_lv_obj_set_style_min_height(PikaObj *self, int value, int selector);
void pika_lvgl_lv_obj_set_style_min_width(PikaObj *self, int value, int selector);
void pika_lvgl_lv_obj_set_style_opa(PikaObj *self, int value, int selector);
void pika_lvgl_lv_obj_set_style_outline_color(PikaObj *self, PikaObj* value, int selector);
void pika_lvgl_lv_obj_set_style_outline_opa(PikaObj *self, int value, int selector);
void pika_lvgl_lv_obj_set_style_outline_pad(PikaObj *self, int value, int selector);
void pika_lvgl_lv_obj_set_style_outline_width(PikaObj *self, int value, int selector);
void pika_lvgl_lv_obj_set_style_pad_bottom(PikaObj *self, int value, int selector);
void pika_lvgl_lv_obj_set_style_pad_column(PikaObj *self, int value, int selector);
void pika_lvgl_lv_obj_set_style_pad_left(PikaObj *self, int value, int selector);
void pika_lvgl_lv_obj_set_style_pad_right(PikaObj *self, int value, int selector);
void pika_lvgl_lv_obj_set_style_pad_row(PikaObj *self, int value, int selector);
void pika_lvgl_lv_obj_set_style_pad_top(PikaObj *self, int value, int selector);
void pika_lvgl_lv_obj_set_style_radius(PikaObj *self, int value, int selector);
void pika_lvgl_lv_obj_set_style_shadow_color(PikaObj *self, PikaObj* value, int selector);
void pika_lvgl_lv_obj_set_style_shadow_ofs_x(PikaObj *self, int value, int selector);
void pika_lvgl_lv_obj_set_style_shadow_ofs_y(PikaObj *self, int value, int selector);
void pika_lvgl_lv_obj_set_style_shadow_opa(PikaObj *self, int value, int selector);
void pika_lvgl_lv_obj_set_style_shadow_spread(PikaObj *self, int value, int selector);
void pika_lvgl_lv_obj_set_style_shadow_width(PikaObj *self, int value, int selector);
void pika_lvgl_lv_obj_set_style_size(PikaObj *self, int value, int selector);
void pika_lvgl_lv_obj_set_style_text_align(PikaObj *self, int value, int selector);
void pika_lvgl_lv_obj_set_style_text_color(PikaObj *self, PikaObj* value, int selector);
void pika_lvgl_lv_obj_set_style_text_decor(PikaObj *self, int value, int selector);
void pika_lvgl_lv_obj_set_style_text_letter_space(PikaObj *self, int value, int selector);
void pika_lvgl_lv_obj_set_style_text_line_space(PikaObj *self, int value, int selector);
void pika_lvgl_lv_obj_set_style_text_opa(PikaObj *self, int value, int selector);
void pika_lvgl_lv_obj_set_style_transform_angle(PikaObj *self, int value, int selector);
void pika_lvgl_lv_obj_set_style_transform_height(PikaObj *self, int value, int selector);
void pika_lvgl_lv_obj_set_style_transform_pivot_x(PikaObj *self, int value, int selector);
void pika_lvgl_lv_obj_set_style_transform_pivot_y(PikaObj *self, int value, int selector);
void pika_lvgl_lv_obj_set_style_transform_width(PikaObj *self, int value, int selector);
void pika_lvgl_lv_obj_set_style_transform_zoom(PikaObj *self, int value, int selector);
void pika_lvgl_lv_obj_set_style_translate_x(PikaObj *self, int value, int selector);
void pika_lvgl_lv_obj_set_style_translate_y(PikaObj *self, int value, int selector);
void pika_lvgl_lv_obj_set_style_width(PikaObj *self, int value, int selector);
void pika_lvgl_lv_obj_set_style_x(PikaObj *self, int value, int selector);
void pika_lvgl_lv_obj_set_style_y(PikaObj *self, int value, int selector);
void pika_lvgl_lv_obj_set_width(PikaObj *self, int w);
void pika_lvgl_lv_obj_set_x(PikaObj *self, int x);
void pika_lvgl_lv_obj_set_y(PikaObj *self, int y);
void pika_lvgl_lv_obj_transform_point(PikaObj *self, PikaObj* p, int recursive, int inv);
void pika_lvgl_lv_obj_update_layout(PikaObj *self);

#endif
