/*
 * [Warning!] This file is auto-generated by pika compiler.
 * Do not edit it manually.
 * The source code is *.pyi file.
 * More details: 
 * English Doc:
 * https://pikadoc-en.readthedocs.io/en/latest/PikaScript%20%E6%A8%A1%E5%9D%97%E6%A6%82%E8%BF%B0.html
 * Chinese Doc:
 * http://pikapython.com/doc/PikaScript%20%E6%A8%A1%E5%9D%97%E6%A6%82%E8%BF%B0.html
 */

#ifndef __pika_lvgl_textarea__H
#define __pika_lvgl_textarea__H
#include <stdio.h>
#include <stdlib.h>
#include "PikaObj.h"

PikaObj *New_pika_lvgl_textarea(Args *args);

void pika_lvgl_textarea___init__(PikaObj *self, PikaObj* parent);
void pika_lvgl_textarea_add_char(PikaObj *self, int c);
void pika_lvgl_textarea_add_text(PikaObj *self, char* txt);
void pika_lvgl_textarea_clear_selection(PikaObj *self);
void pika_lvgl_textarea_cursor_down(PikaObj *self);
void pika_lvgl_textarea_cursor_left(PikaObj *self);
void pika_lvgl_textarea_cursor_right(PikaObj *self);
void pika_lvgl_textarea_cursor_up(PikaObj *self);
void pika_lvgl_textarea_del_char(PikaObj *self);
void pika_lvgl_textarea_del_char_forward(PikaObj *self);
char* pika_lvgl_textarea_get_accepted_chars(PikaObj *self);
int pika_lvgl_textarea_get_cursor_click_pos(PikaObj *self);
int pika_lvgl_textarea_get_cursor_pos(PikaObj *self);
PikaObj* pika_lvgl_textarea_get_label(PikaObj *self);
int pika_lvgl_textarea_get_max_length(PikaObj *self);
int pika_lvgl_textarea_get_one_line(PikaObj *self);
int pika_lvgl_textarea_get_password_mode(PikaObj *self);
int pika_lvgl_textarea_get_password_show_time(PikaObj *self);
char* pika_lvgl_textarea_get_placeholder_text(PikaObj *self);
char* pika_lvgl_textarea_get_text(PikaObj *self);
int pika_lvgl_textarea_get_text_selection(PikaObj *self);
void pika_lvgl_textarea_set_accepted_chars(PikaObj *self, char* list);
void pika_lvgl_textarea_set_align(PikaObj *self, int align);
void pika_lvgl_textarea_set_cursor_click_pos(PikaObj *self, int en);
void pika_lvgl_textarea_set_cursor_pos(PikaObj *self, int pos);
void pika_lvgl_textarea_set_insert_replace(PikaObj *self, char* txt);
void pika_lvgl_textarea_set_max_length(PikaObj *self, int num);
void pika_lvgl_textarea_set_one_line(PikaObj *self, int en);
void pika_lvgl_textarea_set_password_mode(PikaObj *self, int en);
void pika_lvgl_textarea_set_password_show_time(PikaObj *self, int time);
void pika_lvgl_textarea_set_placeholder_text(PikaObj *self, char* txt);
void pika_lvgl_textarea_set_text(PikaObj *self, char* txt);
void pika_lvgl_textarea_set_text_selection(PikaObj *self, int en);
int pika_lvgl_textarea_text_is_selected(PikaObj *self);

#endif
