[env:rpipico2]
platform = https://github.com/maxgerhardt/platform-raspberrypi.git
board = rpipico2w
framework = arduino
board_build.core = earlephilhower
monitor_speed = 115200
board_build.filesystem_size = 0.5m
board_build.f_cpu = 240000000L
extra_scripts = pre:get_git_id.py

lib_deps =
    bodmer/TFT_eSPI @ ^2.5.43
    lvgl/lvgl @ ^8.3.9
    bblanchon/ArduinoJson
    witnessmenow/UniversalTelegramBot @ ^1.3.0
    earlephilhower/ESP8266Audio @ ^1.9.7
    greiman/SdFat

build_flags =
    -D PIKASCRIPT
    -D PIKA_INIT_STRING_ENABLE=1
    ; --- PIKASCRIPT MEMORY CONFIG ---
    ; Stack augmenté pour apps complexes (Wordle, etc.)
    -D PIKA_STACK_BUFF_SIZE=2048
    -D PIKA_LINE_BUFF_SIZE=256
    
    ; --- CONFIG ECRAN WAVESHARE CAPACITIF ---
    -D USER_SETUP_LOADED=1
    -D ST7796_DRIVER=1          ; Nouveau driver pour l'écran capacitif 3.5"
    -D TFT_WIDTH=320
    -D TFT_HEIGHT=480
    
    ; --- COULEURS ---
    ; Attention : Le ST7796S n'a généralement pas besoin de ces corrections.
    ; Je les ai commentées. Si tes couleurs sont inversées (ex: bleu au lieu de rouge), décommente-les !
    ; -D TFT_RGB_ORDER=TFT_BGR
    ; -D TFT_INVERSION_ON
    
    -D LV_COLOR_16_SWAP=1       ; Reste utile avec le DMA du RP2040
    
    ; --- PINS & SPI ---
    -D TFT_SPI_PORT=1
    -D TFT_MISO=12
    -D TFT_MOSI=11
    -D TFT_SCLK=10
    -D TFT_CS=9
    -D TFT_DC=8                 ; CORRECTION : GP8 au lieu de 14
    -D TFT_RST=13               
    -D TFT_BL=15                
    
    -D SPI_FREQUENCY=40000000   ; Tu peux laisser à 60MHz ou descendre à 40MHz si c'est instable
    -D SPI_READ_FREQUENCY=2000000

    ; (SPI_TOUCH_FREQUENCY supprimé car le tactile est maintenant sur I2C)
    
    ; --- LVGL ---
    -D LV_CONF_SKIP
    -D LV_COLOR_DEPTH=16
    -D LV_MEM_SIZE=80000
    -D LV_TICK_CUSTOM=1
    -D LV_DISP_ROT_MAX_BUF=32768
    -D LV_FONT_MONTSERRAT_12=1
    -D LV_FONT_MONTSERRAT_14=1
    -D LV_FONT_MONTSERRAT_18=1
    -D LV_FONT_MONTSERRAT_28=1

    -D LV_USE_QRCODE=1
    -D LV_USE_BARCODE=1

    -D LV_MEM_CUSTOM=1              ; Utilise le malloc système (Gain énorme de flexibilité)
    -D LV_MEMCPY_MEMSET_STD=1       ; Utilise les fonctions C optimisées pour Pico
    -D LV_TICK_CUSTOM=1             ; (Optionnel) Pour la fluidité
    -D LV_DISP_DEF_REFR_PERIOD=15

    -O3