/*
 * [Warning!] This file is auto-generated by pika compiler.
 * Do not edit it manually.
 * The source code is *.pyi file.
 * More details: 
 * English Doc:
 * https://pikadoc-en.readthedocs.io/en/latest/PikaScript%20%E6%A8%A1%E5%9D%97%E6%A6%82%E8%BF%B0.html
 * Chinese Doc:
 * http://pikapython.com/doc/PikaScript%20%E6%A8%A1%E5%9D%97%E6%A6%82%E8%BF%B0.html
 */

#ifndef __pika_lvgl_tabview__H
#define __pika_lvgl_tabview__H
#include <stdio.h>
#include <stdlib.h>
#include "PikaObj.h"

PikaObj *New_pika_lvgl_tabview(Args *args);

void pika_lvgl_tabview___init__(PikaObj *self, PikaObj* parent, int tab_pos, int tab_size);
PikaObj* pika_lvgl_tabview_add_tab(PikaObj *self, char* name);
PikaObj* pika_lvgl_tabview_get_content(PikaObj *self);
int pika_lvgl_tabview_get_tab_act(PikaObj *self);
PikaObj* pika_lvgl_tabview_get_tab_btns(PikaObj *self);
void pika_lvgl_tabview_set_act(PikaObj *self, int id, int anim_en);

#endif
