/*
 * [Warning!] This file is auto-generated by pika compiler.
 * Do not edit it manually.
 * The source code is *.pyi file.
 * More details: 
 * English Doc:
 * https://pikadoc-en.readthedocs.io/en/latest/PikaScript%20%E6%A8%A1%E5%9D%97%E6%A6%82%E8%BF%B0.html
 * Chinese Doc:
 * http://pikapython.com/doc/PikaScript%20%E6%A8%A1%E5%9D%97%E6%A6%82%E8%BF%B0.html
 */

#ifndef __pika_lvgl_indev_t__H
#define __pika_lvgl_indev_t__H
#include <stdio.h>
#include <stdlib.h>
#include "PikaObj.h"

PikaObj *New_pika_lvgl_indev_t(Args *args);

void pika_lvgl_indev_t___init__(PikaObj *self);
void pika_lvgl_indev_t_enable(PikaObj *self, int en);
int pika_lvgl_indev_t_get_gesture_dir(PikaObj *self);
int pika_lvgl_indev_t_get_key(PikaObj *self);
PikaObj* pika_lvgl_indev_t_get_point(PikaObj *self);
int pika_lvgl_indev_t_get_scroll_dir(PikaObj *self);
PikaObj* pika_lvgl_indev_t_get_scroll_obj(PikaObj *self);
int pika_lvgl_indev_t_get_type(PikaObj *self);
void pika_lvgl_indev_t_get_vect(PikaObj *self, PikaObj* point);
void pika_lvgl_indev_t_reset(PikaObj *self, PikaObj* obj);
void pika_lvgl_indev_t_reset_long_press(PikaObj *self);
void pika_lvgl_indev_t_set_button_points(PikaObj *self, PikaObj* points);
void pika_lvgl_indev_t_set_cursor(PikaObj *self, PikaObj* cur_obj);
void pika_lvgl_indev_t_wait_release(PikaObj *self);

#endif
