/*
 * [Warning!] This file is auto-generated by pika compiler.
 * Do not edit it manually.
 * The source code is *.pyi file.
 * More details: 
 * English Doc:
 * https://pikadoc-en.readthedocs.io/en/latest/PikaScript%20%E6%A8%A1%E5%9D%97%E6%A6%82%E8%BF%B0.html
 * Chinese Doc:
 * http://pikapython.com/doc/PikaScript%20%E6%A8%A1%E5%9D%97%E6%A6%82%E8%BF%B0.html
 */

#ifndef __pika_lvgl_ime_pinyin__H
#define __pika_lvgl_ime_pinyin__H
#include <stdio.h>
#include <stdlib.h>
#include "PikaObj.h"

PikaObj *New_pika_lvgl_ime_pinyin(Args *args);

void pika_lvgl_ime_pinyin___init__(PikaObj *self, PikaObj* parent);
PikaObj* pika_lvgl_ime_pinyin_get_cand_panel(PikaObj *self);
PikaObj* pika_lvgl_ime_pinyin_get_kb(PikaObj *self);
void pika_lvgl_ime_pinyin_set_keyboard(PikaObj *self, PikaObj* kb);
void pika_lvgl_ime_pinyin_set_mode(PikaObj *self, int mode);

#endif
