/*
 * [Warning!] This file is auto-generated by pika compiler.
 * Do not edit it manually.
 * The source code is *.pyi file.
 * More details: 
 * English Doc:
 * https://pikadoc-en.readthedocs.io/en/latest/PikaScript%20%E6%A8%A1%E5%9D%97%E6%A6%82%E8%BF%B0.html
 * Chinese Doc:
 * http://pikapython.com/doc/PikaScript%20%E6%A8%A1%E5%9D%97%E6%A6%82%E8%BF%B0.html
 */

#ifndef __pika_lvgl_meter__H
#define __pika_lvgl_meter__H
#include <stdio.h>
#include <stdlib.h>
#include "PikaObj.h"

PikaObj *New_pika_lvgl_meter(Args *args);

void pika_lvgl_meter___init__(PikaObj *self, PikaObj* parent);
PikaObj* pika_lvgl_meter_add_arc(PikaObj *self, PikaObj* scale, int width, PikaObj* color, int r_mod);
PikaObj* pika_lvgl_meter_add_needle_line(PikaObj *self, PikaObj* scale, int width, PikaObj* color, int r_mod);
PikaObj* pika_lvgl_meter_add_scale(PikaObj *self);
PikaObj* pika_lvgl_meter_add_scale_lines(PikaObj *self, PikaObj* scale, PikaObj* color_start, PikaObj* color_end, int local, int width_mod);
void pika_lvgl_meter_set_indicator_end_value(PikaObj *self, PikaObj* indic, int value);
void pika_lvgl_meter_set_indicator_start_value(PikaObj *self, PikaObj* indic, int value);
void pika_lvgl_meter_set_indicator_value(PikaObj *self, PikaObj* indic, int value);
void pika_lvgl_meter_set_scale_major_ticks(PikaObj *self, PikaObj* scale, int nth, int width, int len, PikaObj* color, int label_gap);
void pika_lvgl_meter_set_scale_range(PikaObj *self, PikaObj* scale, int min, int max, int angle_range, int rotation);
void pika_lvgl_meter_set_scale_ticks(PikaObj *self, PikaObj* scale, int cnt, int width, int len, PikaObj* color);

#endif
