/*
 * [Warning!] This file is auto-generated by pika compiler.
 * Do not edit it manually.
 * The source code is *.pyi file.
 * More details: 
 * English Doc:
 * https://pikadoc-en.readthedocs.io/en/latest/PikaScript%20%E6%A8%A1%E5%9D%97%E6%A6%82%E8%BF%B0.html
 * Chinese Doc:
 * http://pikapython.com/doc/PikaScript%20%E6%A8%A1%E5%9D%97%E6%A6%82%E8%BF%B0.html
 */

#ifndef __pika_lvgl_keyboard__H
#define __pika_lvgl_keyboard__H
#include <stdio.h>
#include <stdlib.h>
#include "PikaObj.h"

PikaObj *New_pika_lvgl_keyboard(Args *args);

void pika_lvgl_keyboard___init__(PikaObj *self, PikaObj* parent);
int pika_lvgl_keyboard_get_mode(PikaObj *self);
int pika_lvgl_keyboard_get_selected_btn(PikaObj *self);
PikaObj* pika_lvgl_keyboard_get_textarea(PikaObj *self);
void pika_lvgl_keyboard_set_mode(PikaObj *self, int mode);
void pika_lvgl_keyboard_set_popovers(PikaObj *self, int en);
void pika_lvgl_keyboard_set_textarea(PikaObj *self, PikaObj* ta);

#endif
